bride: !!str Alice
groom: !!str Bob
date: !!timestamp 2017-07-01
languages: !!seq [ fr, en ]
password: !!str secret
contact: !!str offirmo.net+demo-minisite-wedding@gmail.com
mapbox_access_token: !!str <get a token for free by registering on https://www.mapbox.com/>
